import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from '@/components/layouts/Header'
import Footer from '@/components/layouts/Footer'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
        ${inter.className}
        min-h-screen grid grid-rows-[auto,1fr,auto] font-serif
        `}>
          <Header/>
            {children}
          <Footer/>
        </body>
    </html>
  );
}
